# Generated by Django 6.0.8 on 2026-10-01 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('blocked_until', models.DateTimeField(help_text='End of the appointment including the service buffer.')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No-show')], default='confirmed', max_length=16)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price snapshot at booking time.', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.service')),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['business', 'starts_at'], name='bookings_bo_busines_97eb15_idx'), models.Index(fields=['customer', 'starts_at'], name='bookings_bo_custome_8d9abf_idx'), models.Index(fields=['status', 'starts_at'], name='bookings_bo_status_3128b5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='booking_ends_after_start'), models.CheckConstraint(condition=models.Q(('blocked_until__gte', models.F('ends_at'))), name='booking_block_covers_end')],
            },
        ),
    ]
